In [ ]:
# Install pip:

# Download get-pip.py (http://pip.readthedocs.org/en/stable/installing/)
# python3 get-pip.py


# Install package:

# pip3 install numpy

In [6]:
import numpy

print(numpy.array([3, 2, 1]))

[3 2 1]


In [7]:
import numpy as np

print(np.array([1, 2, 3]))





[1 2 3]


In [5]:
from numpy import array

print(array([1, 2, 3]))

[1 2 3]
